import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const observer = readFileSync(new URL('./components/native-session-observer.tsx', import.meta.url), 'utf8')
const adapter = readFileSync(new URL('./native-session-v3-adapter.ts', import.meta.url), 'utf8')
const workThread = readFileSync(new URL('./components/work-thread-conversation.tsx', import.meta.url), 'utf8')
const nativeModel = readFileSync(new URL('./native-session-model.ts', import.meta.url), 'utf8')

assert.ok(observer.includes('import { WorkThreadConversation } from "./work-thread-conversation"'), 'native Session must mount the mature v3 conversation controller')
assert.ok(observer.includes('<WorkThreadConversation'), 'native Session must render the v3 controller directly')
assert.ok(observer.includes('registerNativeSessionV3Adapter'), 'native identity must be translated by the Session-scoped adapter')
assert.ok(observer.includes('controller={controller}'), 'native Session I/O must be injected explicitly into the mature controller')
assert.equal(observer.includes('Continue this Session'), false, 'opening a native Session must never require a visible Continue unlock step')
assert.equal(observer.includes('probeNativeSessionContinuation'), false, 'observer must not acquire ACP writer ownership while opening a Session')
assert.equal(observer.includes('TaskDeskConversation'), false, 'observer must not mount the chat renderer directly')
assert.equal(observer.includes('loadNativeSessionFeed'), false, 'observer must not own transcript loading or paging')
assert.equal(observer.includes('refreshNativeSessionFeed'), false, 'observer must not own a parallel tail refresh')
assert.equal(observer.includes('startTaskDeskSessionLiveRefresh'), false, 'observer must not own a parallel live-event controller')
assert.equal(observer.includes('sendNativeSessionPrompt'), false, 'observer must not own a parallel send controller')
assert.equal(observer.includes('stopNativeSession'), false, 'observer must not own a parallel Stop controller')
assert.equal(observer.includes('ModelSelectionControl'), false, 'observer must not own a parallel model picker')

assert.ok(adapter.includes('async loadMessagePage(config, sessionID, directory, before, limit, refreshHistory)'), 'adapter must observe the pages requested by the v3 controller through its scoped boundary')
assert.equal(adapter.includes('api.loadMessagePage ='), false, 'native Session mounting must not mutate the shared API client')
assert.ok(adapter.includes('!entry.initialPageCaptured || Boolean(before)'), 'initial history and explicit older paging may create compatibility Run identities')
assert.ok(adapter.includes('if (!mayDiscoverRuns) return'), 'tail replay must not manufacture duplicate Runs from changed replay ids')
assert.ok(adapter.includes(':request:${clientRequestId}'), 'new native prompts must use durable client request identity for the compatibility Run')
assert.ok(adapter.includes('probeNativeSessionContinuation(entry.target)'), 'ACP writer acquisition must be deferred to the mutation boundary')
assert.ok(adapter.includes('await ensureWriter(entry)'), 'Send and Stop must acquire writer ownership transparently when needed')
assert.ok(adapter.includes('value === "retry"') && adapter.includes('value === "waiting"'), 'retry and waiting must remain working states')
assert.ok(adapter.includes('stabilizePiTailMessageIDs'), 'PI tail reads must stabilize live ACP ids when the journal later exposes the same reply under a persisted id')
assert.ok(adapter.includes('candidates?.length !== 1'), 'PI identity stabilization must refuse ambiguous repeated-answer matches')
assert.ok(adapter.includes('nextKeyCounts.get(key) !== 1'), 'PI identity stabilization must preserve legitimate repeated identical journal answers')
assert.ok(adapter.includes('entry.target.backend !== "pi" || before'), 'PI identity stabilization must stay scoped to current tail reads and never rewrite older-page history')
assert.ok(adapter.includes('message.info.error'), 'PI identity stabilization must keep interrupted/error turns outside text-only aliasing')
assert.ok(adapter.includes('if (entry && entry.listeners.size === 0) projections.delete(id)'), 'leaving a Session must dispose its transient projection so another Session starts cleanly')
assert.equal(adapter.includes('MAX_CACHED_PROJECTIONS'), false, 'Session projections must not survive navigation in a global cache')
assert.equal(adapter.includes('pruneInactiveProjections'), false, 'Session navigation must not retain inactive projection state')
assert.ok(adapter.includes('reconcileNativeSessionModel(entry, page, before)'), 'every current tail page must refresh delayed OpenCode and Codex model metadata')
assert.ok(adapter.includes('lastNativeMessageModel(page.messages)'), 'OpenCode tail reconciliation must recover the newest native turn model')
assert.equal(adapter.includes('TaskDeskConversation'), false, 'adapter must not contain rendering')
assert.equal(adapter.includes('groupConversationParts'), false, 'adapter must not contain reasoning/activity semantics')

assert.ok(nativeModel.includes('page.model ??'), 'native Session enrichment must consume a model supplied by a native journal page')
// Assert the invariant, not one spelling of it. Freezing the literal guard meant every legitimate
// change to which harnesses expose native model metadata - adding PI, Codex, Claude - broke this
// check while the behaviour it protects was still intact.
assert.ok(nativeModel.includes('PAGE_MODEL_BACKENDS'), 'model enrichment must scope itself with an explicit set of harnesses that expose native model metadata')
assert.match(nativeModel, /if \(target\.backend !== "opencode"[\s\S]{0,200}?\) return target/, 'read-only model enrichment must stay scoped to harnesses with verified native model metadata')
assert.ok(workThread.includes('observedTaskModelKeyRef'), 'the v3 picker must observe a model that arrives after the controller mounted')
assert.ok(workThread.includes('modelSelectionTouchedRef'), 'late native enrichment must not overwrite a model the user explicitly picked')
assert.ok(workThread.includes('currentTaskModelKey === previous'), 'the late-model sync must be edge-triggered rather than resetting the picker on every render')
assert.ok(observer.includes('deferModelFallback'), 'native Sessions must not display the catalog default before native model metadata resolves')
assert.ok(workThread.includes('const fallback = deferModelFallback'), 'the shared controller must preserve ordinary Work Thread fallback behavior')

assert.ok(workThread.includes('const sendInFlightRef = useRef(false)'), 'v3 send in-flight guard must remain authoritative')
assert.ok(workThread.includes('controller.loadMessagePage'), 'v3 transcript paging must remain authoritative')
assert.ok(workThread.includes('startTaskDeskSessionLiveRefresh'), 'v3 live routing must remain authoritative')
assert.ok(workThread.includes('buildWorkThreadTimeline'), 'v3 logical timeline must remain authoritative')

console.log('native Session v3-controller tests passed')