import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const observer = readFileSync(new URL("./components/native-session-observer.tsx", import.meta.url), "utf8")
const panel = readFileSync(new URL("./components/native-session-outcome-panel.tsx", import.meta.url), "utf8")
const client = readFileSync(new URL("./project-outcome-client.ts", import.meta.url), "utf8")
const reviewEvidence = readFileSync(new URL("./native-session-review-evidence.ts", import.meta.url), "utf8")
const desktopTransport = readFileSync(new URL("../electron/request-transport.ts", import.meta.url), "utf8")

assert.ok(observer.includes("<NativeSessionOutcomePanel"), "native Sessions must expose the Project outcome review surface")
assert.ok(observer.includes("conversation={conversation}"), "outcome review must receive the structured native runtime lifecycle")
assert.ok(observer.includes("working={nativeSessionIsWorking(conversation.status)}"), "outcome refresh must follow the native turn lifecycle rather than token events")
assert.ok(observer.indexOf("<NativeSessionOutcomePanel") < observer.indexOf("<WorkThreadConversation"), "outcome review must remain outside the mature composer")
assert.equal(panel.includes("WorkThreadConversation"), false, "Project outcome must not become another conversation controller")
assert.ok(panel.includes("if (!interactionEnabled || working) {"), "Project outcome reads must pause while a turn is working or the machine is reconnecting")
assert.ok(panel.includes("{ ...current.attention, complete: false }"), "working/reconnect boundaries must invalidate stale verified-empty attention before completion can be shown")
assert.ok(panel.includes("listMachineProjects(target.config)"), "outcome must resolve through the daemon canonical Project catalog")
assert.ok(panel.includes("resolveSourceSessionProject(target, projects)"), "outcome must derive the local Project from the current Session only")
assert.ok(panel.includes("loadMachineProjectOutcome(target.config, projectRoute.id)"), "outcome reads must use the sanitized catalog Project id, never a caller path")
assert.ok(panel.includes("api.loadQuestions(target.config, target.directory)"), "review evidence must come from the native structured question endpoint")
assert.ok(panel.includes("api.loadPermissions(target.config, target.directory)"), "review evidence must come from the native structured permission endpoint")
assert.ok(panel.includes("request.sessionID === target.sessionID"), "attention evidence must stay scoped to the exact native Session")
assert.ok(panel.includes('questionResult.status === "fulfilled"'), "a successful question read must be retained even if permission enrichment fails")
assert.ok(panel.includes('permissionResult.status === "fulfilled"'), "a successful permission read must be retained even if question enrichment fails")
assert.ok(panel.includes("complete: attentionResult.value.questions !== undefined && attentionResult.value.permissions !== undefined"), "Completed must require both attention sources to be freshly verified")
assert.ok(panel.includes("Promise.allSettled"), "Project and attention enrichment must fail independently instead of blocking Session review")
assert.equal(panel.includes("loadDiff"), false, "generic outcome review must not depend on a harness-specific diff endpoint")
assert.equal(panel.toLowerCase().includes("test passed"), false, "checks must not be inferred from transcript/UI prose")
assert.ok(panel.includes("MAX_VISIBLE_FILES = 12"), "outcome UI must stay bounded even when the daemon returns a larger safe snapshot")
assert.ok(panel.includes("omitted by safety or display bounds"), "hidden/bounded file names must remain visible as an explicit incomplete-evidence signal")
assert.ok(panel.includes("const diffSummary = outcome?.diffSummary"), "bounded Git change totals must be shown from Project outcome metadata")
assert.ok(panel.includes("Lines <strong>+{diffSummary.insertions} / −{diffSummary.deletions}</strong>"), "outcome must make added/removed line totals easy to read")
assert.ok(panel.includes("Tracked <strong>{diffSummary.trackedFiles}"), "outcome must expose the tracked-file aggregate without loading diff contents")

assert.ok(reviewEvidence.includes("attention.permissions > 0"), "known target permission must remain visible even when another attention source is unavailable")
assert.ok(reviewEvidence.includes("attention.questions > 0"), "known structured questions must remain visible even when another attention source is unavailable")
assert.ok(reviewEvidence.includes('conversation.status === "failed"'), "structured runtime failure must be review evidence")
assert.ok(reviewEvidence.includes('conversation.status === "cancelled"'), "structured cancellation must remain visible")
assert.ok(reviewEvidence.includes("!attention.complete || !hasRealTurn(conversation)"), "completion must be withheld until attention is verified and a real turn exists")
assert.equal(reviewEvidence.includes("messageText"), false, "review evidence must never parse assistant transcript text")
assert.equal(reviewEvidence.includes("MessageEnvelope"), false, "review evidence must not inspect transcript envelopes")

assert.ok(client.includes("404 || status === 405 || status === 501"), "older daemons must degrade optional outcome metadata without blocking Session open")
assert.ok(client.includes("normalized.split(\"/\").some((part) => part === \"..\")"), "client must defense-in-depth reject escaping paths")
assert.ok(client.includes("payload.projectId !== projectId"), "outcome response must stay bound to the exact requested Project")
assert.ok(client.includes("diffSummary?: MachineProjectOutcomeDiffSummary"), "outcome wire contract must explicitly model bounded aggregate diff evidence")
assert.ok(client.includes("safeDiffSummary(source.diffSummary)"), "aggregate diff evidence must be sanitized before entering UI state")
assert.equal(client.includes("/diff"), false, "outcome client must never request a raw diff endpoint")
assert.equal(client.includes("patch"), false, "outcome client must not carry patch contents")
assert.equal(client.includes("hunk"), false, "outcome client must not carry diff hunks")

assert.ok(desktopTransport.includes("v1\\/project-(?:identity|outcome)"), "desktop Project metadata must stay on the machine daemon instead of being agent scoped")

console.log("native Session Project outcome tests passed")
