import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const read = (name) => readFileSync(new URL(name, import.meta.url), 'utf8')
const discovery = read('./native-session-discovery.ts')
const continuation = read('./native-session-continuation.ts')
const create = read('./native-session-create.ts')
const prompt = read('./native-session-prompt.ts')
const stop = read('./native-session-stop.ts')
const adapter = read('./native-session-v3-adapter.ts')
const modelRecovery = read('./native-session-model.ts')
const observer = read('./components/native-session-observer.tsx')
const home = read('./components/native-session-home.tsx')
const actions = read('./components/native-session-actions.tsx')
const rename = read('./components/native-session-rename.tsx')
const workThread = read('./components/work-thread-conversation.tsx')
const liveRefresh = read('./taskdesk-session-live-refresh.ts')
const timeline = read('./work-thread-timeline.ts')
const conversation = read('./components/taskdesk-conversation.tsx')
const messageContent = read('./components/taskdesk-message-content.tsx')
const handoff = read('./components/native-session-handoff-control.tsx')
const standalone = read('./components/standalone-universal-workspace.tsx')
const daemon = read('../../bridge/src/machine-daemon.js')
const daemonCli = read('../../bridge/src/daemon-cli.js')

// Product identity is Machine -> Project -> real native Session. The failed Conversation-first UI
// is deliberately gone and these guards make its accidental reintroduction a regression.
assert.equal(existsSync(new URL('./components/conversation-workspace.tsx', import.meta.url)), false, 'retired Conversation workspace must stay deleted')
assert.equal(existsSync(new URL('./components/conversation-detail.tsx', import.meta.url)), false, 'retired Conversation detail must stay deleted')
assert.ok(discovery.includes('export type NativeSessionRef'), 'Session-first must keep native Session identity explicit')
assert.ok(discovery.includes('machineID: string') && discovery.includes('agentID: string') && discovery.includes('sessionID: string'), 'native identity must include machine, harness and native Session id')
assert.ok(discovery.includes('listGlobalSessions(config).catch(() => client.listSessions(config))'), 'native discovery must retain global-list fallback')
assert.ok(discovery.includes('renameSupported: agent.capabilities?.sessionRename === true'), 'native discovery must expose rename capability from the harness contract')
assert.ok(discovery.includes('deleteSupported: agent.capabilities?.sessionDelete === true'), 'native discovery must expose delete capability from the harness contract')
assert.equal(discovery.includes('createTask('), false, 'discovery must not persist a Task')
assert.equal(discovery.includes('launch('), false, 'discovery must not launch work')

assert.ok(continuation.includes('client.claimSession(target.config, target.directory, target.sessionID)'), 'ACP mutation must still claim the exact native Session when ownership is needed')
assert.equal(continuation.includes('createSession('), false, 'same-Session continuation must not create a replacement Session')

assert.ok(create.includes('api.createSession(config'), 'New Session must reuse the existing native /session create primitive')
assert.ok(create.includes('agent.transport === "acp" || agent.transport === "http"'), 'PI native create must remain on the validated shared ACP transport')
assert.ok(create.includes('agent.backend === "opencode" && agent.transport === "http"') || create.includes('agent.transport === "acp" || agent.transport === "http"'), 'OpenCode native create must remain on its validated managed HTTP transport')
assert.ok(create.includes('writerOwned: true'), 'a freshly created native Session must enter the v3 controller as already writable')
assert.equal(create.includes('createTask('), false, 'native create must not create a Task')
assert.equal(create.includes('Conversation'), true, 'native create comments must explicitly document the no-Conversation boundary')
assert.ok(home.includes('aria-label={t("sf.newSession")}'), 'Session Home must expose translated New Session')
assert.ok(home.includes('createNativeSessionTarget'), 'Session Home must create a real native Session rather than a Task')
assert.ok(home.includes('canCreateNativeSession'), 'Session Home must expose only harness transports that passed native create parity')
assert.ok(home.includes('aria-label={t("sf.filterByMachine")}') && home.includes('t("sf.allMachinesCount"'), 'multi-machine navigation must offer an explicit All/single-machine filter')

// Rename/Delete act on the open native Session in its header, not on whichever row happens to be
// selected in the navigation rail. Rename is an inline edit of that header's heading; Delete keeps
// its confirmation panel, because it is not reversible.
assert.equal(home.includes('api.renameSession('), false, 'Session navigation must not own rename mutations')
assert.equal(home.includes('api.deleteSession('), false, 'Session navigation must not own delete mutations')
assert.ok(rename.includes('api.renameSession(target.config, target.sessionID'), 'open Session action must rename the real native Session')
assert.ok(actions.includes('api.deleteSession(target.config, target.sessionID'), 'open Session action must delete the real native Session')
assert.ok(rename.includes('target.renameSupported') && actions.includes('target.deleteSupported'), 'native metadata actions must follow harness capabilities')
assert.ok(actions.includes('t("sf.keepSession")') && actions.includes('t("sf.deleteSession")'), 'native deletion must use an inline translated confirmation')
assert.equal(actions.includes('window.confirm'), false, 'native deletion must not use a blocking browser dialog')

assert.ok(prompt.includes('clientRequestId'), 'native prompts must retain durable mutation identity')
assert.ok(prompt.includes('loadPendingNativeSessionPrompt'), 'lost-response retries must reuse the unresolved request id')
assert.ok(prompt.includes('`/session/${encodeURIComponent(target.sessionID)}/prompt`'), 'native prompt must use the idempotent daemon endpoint')
assert.ok(stop.includes('clientRequestId') && stop.includes('operationToken'), 'native Stop must retain durable per-turn mutation identity')

assert.ok(observer.includes('import { WorkThreadConversation } from "./work-thread-conversation"'), 'native Session detail must mount the mature v3 controller')
assert.ok(observer.includes('<WorkThreadConversation'), 'native Session detail must render WorkThreadConversation directly')
assert.ok(observer.includes('registerNativeSessionV3Adapter'), 'observer must limit Session-first behavior to a compatibility adapter')
assert.ok(observer.includes('unregisterNativeSessionV3Adapter'), 'observer must cleanly unmount the compatibility adapter')
assert.ok(observer.includes('loadNativeSessionSnapshot'), 'observer must read native Session state through the adapter')
assert.ok(observer.includes('nativeSessionEventScope'), 'observer must scope live events to the selected native Session')
assert.ok(observer.includes('connectEventStream'), 'observer must retain live event delivery')
assert.ok(observer.includes('taskdeskSessionLiveRefresh'), 'observer must route live refresh through the shared Session controller')
assert.equal(observer.includes('setInterval('), false, 'observer must not poll the selected native Session')
assert.ok(workThread.includes('TaskDeskConversation'), 'native Session conversation must reuse the shared mature chat renderer')
assert.ok(workThread.includes('submitTaskDeskComposer'), 'native Session composer must reuse shared mature submit semantics')
assert.ok(workThread.includes('requestTaskDeskStop'), 'native Session Stop must reuse shared mature stop semantics')
assert.ok(workThread.includes('applyConversationController'), 'native Session transcript must reuse shared mature ordering/dedup semantics')
assert.ok(workThread.includes('mergeNewestMessagePage'), 'native Session transcript must preserve bounded newest-page reconciliation')
assert.ok(workThread.includes('mergeOlderMessagePage'), 'native Session transcript must preserve bounded older-page reconciliation')
assert.ok(liveRefresh.includes('session.updated'), 'ACP Session lifecycle events must refresh the selected Session')
assert.ok(timeline.includes('buildWorkThreadTimeline'), 'shared timeline must remain the visible conversation truth')
assert.ok(conversation.includes('TaskDeskMessageContent'), 'shared conversation renderer must retain structured message content')
assert.ok(messageContent.includes('Markdown'), 'shared message content must retain Markdown rendering')
assert.ok(handoff.includes('native Session'), 'handoff UI must remain explicit about native Session identity')
assert.ok(standalone.includes('NativeSessionHome'), 'standalone workspace must remain Session-first')
assert.ok(daemon.includes('createMachineDaemon'), 'machine daemon must remain the multi-harness control plane')
assert.ok(daemonCli.includes('runMachineDaemon'), 'daemon CLI must still launch the machine daemon')

console.log('Session-first regression checks passed')
